services:
  goravel:
    build:
      context: .
    env_file:
      - ./.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${APP_HOST}:${APP_PORT}:${APP_PORT}"
    restart: always
    networks:
      - ponta_network

networks:
  ponta_network:
    external: true
