services:
  goravel:
    build:
      context: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${APP_HOST}:${APP_PORT}:${APP_PORT}"
    networks:
      - bridge-network
    restart: always

networks:
  bridge-network:
    name: bridge
    external: true
