version: '3'

services:
  goravel:
    build:
      context: .
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${APP_HOST}:${APP_PORT}:${APP_PORT}"
    networks:
      - bridge-network
    restart: always

networks:
  bridge-network:
    # Sử dụng mạng bridge đã tồn tại (bên ngoài Docker) — sử dụng external: true
    # Đảm bảo mạng này tồn tại trước khi khởi chạy: docker network ls
    external: true
